[package]
name = "stest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
sycamore = "0.6.3"
sycamore-router = "0.6.3"
tracing = "0.1.29"
tracing-wasm = "0.2.0"
